# Generated by Django 4.1.4 on 2022-12-29 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_purchase_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirement',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.ingredient'),
        ),
    ]
